# Generated by Django 3.0.6 on 2020-05-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coureser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
    ]
