# Generated by Django 3.0.6 on 2020-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coureser', '0005_auto_20200519_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
