# Generated by Django 3.0.6 on 2020-05-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coureser', '0006_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
